### ISSUE TITLE
BDD voyages d'affaires

### ISSUE THREAD

**Issue by marchanderic44** [SteevenJanny/InformatiquePourTous-CPGE#1]
Bonjour,
Est-il possible d'obtenir la base de données des "voyages d'affaires" utilisée comme exemple sur le cours du 3ème semestre des BDD de votre ouvrage ?
Merci

**Comment by SteevenJanny** [comment]
Bonjour,
Merci pour votre interêt ! La base de données utilisée dans l'exercice était factice, mais nous avons mis en place une version utilisable pour tester les commandes du cours. Elle est maintenant disponible ici : 3e_SEMESTRE/Langage_SQL.
