### ISSUE TITLE
Exercice 1 Théorie des Jeux

### ISSUE THREAD

**Issue by ArnaudBegyn** [SteevenJanny/InformatiquePourTous-CPGE#2]
Il manque la correction.

**Comment by SteevenJanny** [comment]
Bonjour,
Veuillez préciser votre question. L'exercice 1 du chapitre de Théorie des Jeux est un exercice théorique dont la correction est bien disponible dans le livre.

**Comment by ArnaudBegyn** [comment]
Autant pour moi je ne l'avais pas vue.
