### ISSUE TITLE
Bug programme morpion

### ISSUE THREAD

**Issue by ArnaudBegyn** [SteevenJanny/InformatiquePourTous-CPGE#3]
Bonjour
Dans le programme fourni pour jouer au morpion contre l'IA, le programme plante si on fait match nul.
Dans le programme principal vous avez prévu que les deux joueurs jouent à chaque tour, mais en cas de match nul un seul joueur joue au dernier tour.

**Comment by SteevenJanny** [comment]
Merci pour votre retour, cette erreur a été corrigée.
